### ISSUE TITLE
HyperText --> Hypertext

### ISSUE THREAD

**Issue by dongwon210** [sagarjoglekar/ht2018#11]
From: Mark Bernstein <bernstein@eastgate.com>
To: dongwon@psu.edu, ella@aalto.fi
Subject: Hypertext 2018
Parts/Attachments:
   1   OK    ~26 lines  Text
   2 Shown   ~43 lines  Text
----------------------------------------

May I trouble you with a minor mishap regarding the Hypertext 2018 conference web site?
The title of the site reads as follows:

<title>ACM HyperText 2018</title>

But hypertext is not camel-cased. It’s been the ACM Hypertext Conference since 1987 (though the first
installment was a workshop, not a conference).

The camelCase form also appears in the copyright notice in the page footer, though not (as far as I
noticed) elsewhere.

**Comment by sagarjoglekar** [comment]
Fixed camel cases
