### ISSUE TITLE
Misc items from Dec 2017.

### ISSUE THREAD

**Issue by dongwon210** [sagarjoglekar/ht2018#12]
- calls via the blue rectangle in the "calls" do not show due
information. however, if i follow the link to blue sky from the "news"
section, it correctly shows due info.

- see the attachment (from both chrome and firefox on my mac). font
sizes differ and there is big gap between two parts.

- in it, the link to the template is associated with the text "
submission template and are to be submitted using the same", confusing
the next link to the submission site. pls associate the link to the
template with only "template" to make two links distinct.

- "Submissions to be done on our Easy Chair website": link to
  easychair site here, at 4th bullet, leads to "not found" error.

**Comment by sagarjoglekar** [comment]
I could not find any font differences between chrome and firefox on my side. Also the attachment was missing, so did not get what you were describing. However other issues seem to be fixed. Also font pairings are managed by Bootstrap which we are using out of the box for responsiveness of the page. I will look in to this some more.

**Comment by dongwon210** [comment]
it's attached.
