### ISSUE TITLE
update keynote speaker info

### ISSUE THREAD

**Issue by gvrkiran** [sagarjoglekar/ht2018#16]
see email from Dongwon.

Also, I’ve attached a couple of more recent photos that might be better.

Bio:
Ben Zhao is the Neubauer Professor of Computer Science at University of Chicago.  He completed his PhD from Berkeley (2004) and his BS from Yale (1997). He is an ACM distinguished scientist, and recipient of the NSF CAREER award, MIT Technology Review's TR-35 Award (Young Innovators Under 35), ComputerWorld Magazine's Top 40 Tech Innovators award, Google Faculty award, and IEEE ITC Early Career Award. His work has been covered by media outlets such as New York Times, Boston Globe, LA Times,
MIT Tech Review, and Slashdot. He has published more than 150 publications in areas of security and privacy, networked systems,
wireless networks, data-mining and HCI (H-index 58). His most recent work looks closely at the role of machine learning and neural networks in generating and detecting synthetic and altered content online.  He recently served as TPC co-chair for the World Wide Web Conference (WWW 2016) and will be PC-chair for the upcoming ACM Internet Measurement Conference (IMC 2018).

**Comment by sagarjoglekar** [comment]
Done
