### ISSUE TITLE
Another keynote bio: Leslie Sage

### ISSUE THREAD

**Issue by dongwon210** [sagarjoglekar/ht2018#17]
Use the photo here: https://lesliesage.github.io/

Bio: Dr. Sage is the Director of Data Science at DevResults, a software company that provides a data management platform for the international development community. Working with data in this sphere presents unique challenges. The challenge at DevResults is to design tools that work anywhere in the world for someone with any level of experience with technology and data. The aim of her team is not to provide analysis as a service but to enable data-driven decision-making by the folks doing the work in developing communities. Previously, she worked with the Obama Presidential Campaign in 2012 as Deputy Data Director for the battleground state of Iowa. In that position, she leveraged voter models to allocate campaign resources, created up-to-the-minute dashboards for decision-makers, and discovered Midwestern craft beers. She holds a Ph.D. in Microvascular Physiology from the University of Bristol in England. Her research took her to the Hospital for Infectious Diseases in Ho Chi Minh City, Vietnam, where she collaborated with the Gates Foundation and Oxford University to develop a new way to study dengue infection.

**Comment by dongwon210** [comment]
CHANGE--pls use the following
---


Leslie Sage is the Director of Data Science at DevResults, a software company that provides a data management platform for the international development community. She has implemented DevResults software for use in over 60 countries by clients overseeing billion-dollar international development organizations and created training programs in data management.

Previously, Leslie worked with the Obama Presidential Campaign in 2012 as Deputy Data Director for the battleground state of Iowa. In that position Leslie leveraged voter models to allocate campaign resources, created up-to-the-minute dashboards for decision-makers, and discovered Midwestern craft beers.

Leslie hold a Ph.D. in Microvascular Physiology from the University of Bristol in England (2012) and a B.A. in Cognitive Science from Rice University (2004). Her research took her to the Hospital for Infectious Diseases in Ho Chi Minh City, Vietnam, where she collaborated with the Gates Foundation and Oxford University to develop a new way to study dengue infection.

**Comment by sagarjoglekar** [comment]
Done
