### ISSUE TITLE
New Keynote: Elizabeth Kittrie

### ISSUE THREAD

**Issue by dongwon210** [sagarjoglekar/ht2018#20]
Will email photo

---
Elizabeth Kittrie is a Strategic Advisor for Data and Open Science at the National Library of Medicine (NLM) where she is involved in developing the NLM long-range strategic plan and leading data science and open science initiatives.  Prior to joining to the NLM, she served as a Senior Advisor to the Associate Director for Data Science at the National Institutes of Health, where she led open innovation efforts including the Open Science Prize, a collaborative partnership between the NIH, Wellcome Trust and Howard Hughes Medical Institute. Kittrie has also served as Senior Advisor to the Chief Technology Officer of the U.S. Department of Health and Human Services, where she led open government activities across HHS and coordinated the Department’s efforts to develop a common Public Access Policy.  Prior to joining HHS, Kittrie served as the first Associate Director for the Department of Biomedical Informatics at Arizona State University.

**Comment by sagarjoglekar** [comment]
Done, I have temporarily used the image from https://www.rd-alliance.org/users/elizabeth-kittrie will update once you send it.

**Comment by dongwon210** [comment]
Sagar, I emailed her photo to u last night.

---
Sent from LG3




On Thu, Jan 25, 2018 at 7:43 AM -0500, "Sagar Joglekar" <notifications@github.com<mailto:notifications@github.com>> wrote:


Done, I have temporarily used the image from https://www.rd-alliance.org/users/elizabeth-kittrie will update once you send it.

-

**Comment by sagarjoglekar** [comment]
Sorry, My bad. The attachement missed me entirely. I have updated the picture. Check it out when you have time. 
Sagar

**Comment by dongwon210** [comment]
thanks--looks good.

>   
>   Sorry, My bad. The attachement missed me entirely. I have updated the picture. Check it out when you
>   have time.
>   Sagar
>   
>   —
>   You are receiving this because you authored the thread.
>   Reply to this email directly, view it on GitHub, or mute the
>   thread.[ALMn9HG9ym8aiEMP3k5TAX4GKludyIZaks5tOIYTgaJpZM4RsIZw.gif]
>   
>   
>   


---
Dongwon Lee	http://pike.psu.edu/dongwon
