### ISSUE TITLE
Add Mark Bernstein to Blue Sky Ideas track

### ISSUE THREAD

**Issue by nishrs** [sagarjoglekar/ht2018#21]
Sagar, Kiran, please can you add Mark Bernstein to the list of people evaluating the Blue Sky ideas track: 

ie., in the “Call for Blue Sky Ideas” at https://ht.acm.org/ht2018/
we have the line: 

All submissions to this special track will be evaluated by a dedicated committee consisting of Krishna Gummadi, David Millard, Charlie Hargood, Nishanth Sastry and Ingmar Weber. 

Please change this to the following:

All submissions to this special track will be evaluated by a dedicated committee consisting of Mark Bernstein, Krishna Gummadi, Charlie Hargood, David Millard, Nishanth Sastry and Ingmar Weber.  (Note new order is lexicographic). 

Ideally we want a separate page listing our affiliations as well: 

Mark Bernstein - Eastgate
Krishna Gummadi - Max Planck Institute for Software Systems
Charlie Hargood - Bournemouth University
David Millard - University of Southampton 
Nishanth Sastry - King's College London
Ingmar Weber - Qatar Computing Research Institute

**Comment by gvrkiran** [comment]
Done
