### ISSUE TITLE
Head bar menu

### ISSUE THREAD

**Issue by sagarjoglekar** [sagarjoglekar/ht2018#3]
The main title menu of the website is too small and cannot pack more of the salient pages. Try to find a solution out

**Comment by sagarjoglekar** [comment]
I have made some space here, But adding dropdown messes up. The dropdown hides behind the overlay. Trying to fix that

**Comment by gvrkiran** [comment]
I tried this, but it does not look easy. I just fixed the menu by reducing the spacing between the links. If we need to add more, we can also decrease the font or remove some links after some time (like deadlines). I think it should suffice.

**Comment by sagarjoglekar** [comment]
I think some changes broke the menu height https://www.dropbox.com/s/xu75l4d9w6pl64s/Screenshot%202018-01-30%2014.35.18.png?dl=0
I had done some changes to the menu when I added the registration info.. Could there be some conflicts with yours and mine ?
