### ISSUE TITLE
Important dates section - can it appear in the main div rather than a column on the side?

### ISSUE THREAD

**Issue by nishrs** [sagarjoglekar/ht2018#6]

**Comment by sagarjoglekar** [comment]
I would argue that the current layout works, because you can just go to https://ht.acm.org/ht2018/#About and see the details of conference as well as dates to look for in the same screen. Let me know if you still need it to be under About.

**Comment by nishrs** [comment]
You are seeing this because you know where the content is. The eyes are drawn more to the bigger main div. For new visitors to the sites I feel it may be easier to add another section under the About, and name it Important Dates. The link from "important dates" at the beginning of the webpage can link directly there.
