### ISSUE TITLE
Accepted workshops - title of the second and third workshops does not appear in Red

### ISSUE THREAD

**Issue by nishrs** [sagarjoglekar/ht2018#7]
Human Factors in Hypertext
and 
Narrative and Hypertext (NHT18)

needs to be in Red.

**Comment by sagarjoglekar** [comment]
Do the other two workshops have Web pages, If yes I will link them up. The first one is Red because its linked to their official page. If not I can make a placeholder link

**Comment by nishrs** [comment]
I mean, create a linkable URL for each workshop, with whatever info is 
already there. Again, this is just to be able to share the URL with 
people who ask.
